[lint]
select = [
    "ANN",
    "B",
    "A",
    "C4",
    "ISC",
    "PIE",
    "Q",
    "RSE",
    "RET",
    "SIM",
    "SLOT",
    "TID",
    "TD",
    "TC",
    "ARG",
    "FLY",
    "I",
    "E",
    "W",
    "D",
    "F",
    "PGH",
    "PL",
    "UP",
    "RUF",
    "TRY",
    "FURB",
]
ignore = [
    "ANN001",
    "ANN201",
    "ANN206",
    "SIM105",
    "TID252",
    "TD002",
    "TD003",
    "ARG003",
    "E501",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D212",
    "D301",
    "D400",
    "D415",
    "RUF001",
    "RUF002",
    "RUF003",
    "RUF005",
    "RUF012",
    "PLC0415",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLW1510",
    "PLW2901",
    "UP015",
    "TRY002",
    "TRY003",
    "TRY301",
]
