name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U loguru
        pip install -U nuitka
    - name: Building the application
      run: |
        python -m nuitka --standalone --onefile --assume-yes-for-downloads --plugin-enable=tk-inter --output-dir=easyrip_nuitka_output src/easy_rip.py
    - name: Store the artifact
      uses: actions/upload-artifact@v4
      with:
        name: easyrip
        path: easyrip_nuitka_output/*.exe
